# Generated by Django 4.2.1 on 2023-10-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('numHuespedes', models.IntegerField()),
                ('numCamas', models.IntegerField(blank=True, null=True)),
                ('numBanos', models.IntegerField()),
                ('acercaEspacio', models.TextField()),
                ('espacio', models.TextField()),
                ('accesoHuespedes', models.TextField()),
                ('aspectosDestacar', models.TextField()),
                ('numeroRegistro', models.CharField(max_length=30)),
                ('valorNoche', models.IntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('desLugar', models.TextField()),
                ('direccion', models.CharField(max_length=100)),
                ('continente', models.CharField(max_length=50)),
                ('valorLimpieza', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('politica', models.BooleanField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadanía'), ('CE', 'Cedula de Extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'Número de identificación tributaria')], default='CC', max_length=3)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('telefonoCelular', models.CharField(max_length=12)),
                ('idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('rolAdmin', models.BooleanField(blank=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('banco', models.CharField(choices=[('1', 'BANCOLOMBIA'), ('2', 'Banco de Bogotá'), ('3', 'Banco caja social'), ('4', 'Av Villas'), ('5', 'Banco de occidente'), ('6', 'Banco Popular'), ('7', 'Banco Agrario'), ('8', 'Davivienda'), ('9', 'Colpatria')], default='1', max_length=2)),
                ('numeroCuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('daviplata', models.CharField(blank=True, max_length=12, null=True)),
                ('tiempo', models.IntegerField()),
                ('calificacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SitiosVisitados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVista', models.DateField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icono', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icono', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('numAdultos', models.IntegerField()),
                ('numNinos', models.IntegerField(blank=True, null=True)),
                ('numBebes', models.IntegerField(blank=True, null=True)),
                ('numMascotas', models.IntegerField(blank=True, null=True)),
                ('precioFinal', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('comision', models.IntegerField()),
                ('gananciaAnfitrion', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icono', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='PagoAnfitrion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRadicado', models.DateField()),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('medioPago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('medioPago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('valorDevolucion', models.IntegerField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('calLimpieza', models.FloatField()),
                ('calComunicacion', models.FloatField()),
                ('calLlegada', models.FloatField()),
                ('calFiabilidad', models.FloatField()),
                ('calUbicacion', models.FloatField()),
                ('calPrecio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
    ]
