# Generated by Django 4.2.1 on 2023-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='continente',
            field=models.CharField(choices=[('AMÉRICA DEL SUR', 'AMÉRICA DEL SUR'), ('AMÉRICA DEL NORTE', 'AMÉRICA DEL NORTE'), ('CENTRO AMÉRICA', 'CENTRO AMÉRICA'), ('EUROPA', 'EUROPA'), ('ASIA', 'ASIA'), ('ÁFRICA', 'ÁFRICA'), ('OCEANÍA', 'OCEANÍA')], default='AMÉRICA DEL NORTE', max_length=50),
        ),
    ]
