# Generated by Django 4.2.1 on 2023-10-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0003_remove_regla_icono_remove_regla_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaRegistro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
