# Generated by Django 4.2.1 on 2023-09-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('icono', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria')], default='CC', max_length=3)),
                ('numDocumento', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=12)),
                ('telefonoCel', models.CharField(max_length=12)),
                ('idioma', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cuentaBancaria', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=30)),
                ('daviplata', models.CharField(max_length=12)),
                ('rolAdmin', models.BooleanField()),
                ('rolAnfi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('huespedes', models.IntegerField()),
                ('camas', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('acercaEspacio', models.TextField()),
                ('espacio', models.TextField()),
                ('accesoHuesped', models.TextField()),
                ('aspectoDestacar', models.TextField()),
                ('numRegistro', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=50)),
                ('lugarDes', models.TextField()),
                ('direccion', models.CharField(max_length=150)),
                ('continente', models.CharField(max_length=60)),
                ('valorNoche', models.IntegerField()),
                ('valorLimpieza', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('politica', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('numAdultos', models.IntegerField()),
                ('numNiños', models.IntegerField()),
                ('numBebes', models.IntegerField()),
                ('numMascotas', models.IntegerField()),
                ('medioPago', models.TextField(max_length=60)),
                ('estado', models.TextField(max_length=40)),
                ('precioFinal', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('gananciaAnf', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calLimpieza', models.IntegerField()),
                ('calComunicacion', models.IntegerField()),
                ('calLlegada', models.IntegerField()),
                ('calFiabilidad', models.IntegerField()),
                ('calUbicacion', models.IntegerField()),
                ('calPrecio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.usuario')),
            ],
        ),
    ]
