# Generated by Django 4.2.1 on 2023-09-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRadicado', models.DateField()),
                ('fechaPago', models.DateField()),
                ('medioPago', models.TextField(max_length=60)),
                ('estado', models.TextField(max_length=40)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.reserva')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.usuario')),
            ],
        ),
    ]
