# Generated by Django 4.2.1 on 2023-09-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0002_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pago',
            name='medioPago',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='medioPago',
            field=models.CharField(max_length=60),
        ),
    ]
