# Generated by Django 4.2.1 on 2023-10-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0003_alter_pago_estado_alter_pago_mediopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
