# Generated by Django 4.2.1 on 2023-10-01 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0004_servicio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.sitio')),
            ],
        ),
    ]
