# Generated by Django 4.2.1 on 2023-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_api', '0005_reglaadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
