// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHKttFGtWYpviub_m0_ijKVbOcOym0mSY',
    appId: '1:703130917212:web:bdcd84b258de6163f1c999',
    messagingSenderId: '703130917212',
    projectId: 'proyectofinal-85084',
    authDomain: 'proyectofinal-85084.firebaseapp.com',
    storageBucket: 'proyectofinal-85084.appspot.com',
    measurementId: 'G-ZSJ5653G37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlS_vqSrOhXhsqJqbxQFhg-Xm0wwDZpKM',
    appId: '1:703130917212:android:02f477225632362ef1c999',
    messagingSenderId: '703130917212',
    projectId: 'proyectofinal-85084',
    storageBucket: 'proyectofinal-85084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7AaVZ_imSt5wSzjJp7coXtCgTCN5CVNo',
    appId: '1:703130917212:ios:317e5956469c24d3f1c999',
    messagingSenderId: '703130917212',
    projectId: 'proyectofinal-85084',
    storageBucket: 'proyectofinal-85084.appspot.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7AaVZ_imSt5wSzjJp7coXtCgTCN5CVNo',
    appId: '1:703130917212:ios:5d9c2bb8c68c23e0f1c999',
    messagingSenderId: '703130917212',
    projectId: 'proyectofinal-85084',
    storageBucket: 'proyectofinal-85084.appspot.com',
    iosBundleId: 'com.example.proyectoFinal.RunnerTests',
  );
}
